### ISSUE TITLE
Budgie Desktop - Audio Volume is displayed at wrong size

### ISSUE THREAD

**Issue by Jguer** [erikdubois/Surfn#1]
super-ultra-flat-numix-remix-icons
![super-ultra-flat-numix](https://cloud.githubusercontent.com/assets/8071073/16709874/52dc4ba6-4615-11e6-8f31-b09c3225c3e0.png)

yltra-flat-icons
![yltra-flat](https://cloud.githubusercontent.com/assets/8071073/16709875/52ddbcca-4615-11e6-83d5-53100a6fca75.png)

Desktop: Budgie-Desktop  (Gtk 3.20.6) 
Distro: Arch Linux

**Comment by erikdubois** [comment]
I have noticed that too... not sure what the reason may be - in the follow-up folder
but it is damn ugly

**Comment by erikdubois** [comment]
I found the fix. You can try it again.

**Comment by Jguer** [comment]
Can confirm, Audio volume is displayed at right size on Budgie Desktop
