### ISSUE TITLE
LMMS icon STILL using Ardour

### ISSUE THREAD

**Issue by JesseSteele** [erikdubois/Surfn#10]
I made an issue with this a while back with one of the dev levels. Here it still is:

My Instagram shot:
https://www.instagram.com/p/BT_U8IhhM1O

Feel free to use the LMMS vectors I made just to help you with this:
https://github.com/inkVerb/icons/blob/master/lmms-layers.svg
https://github.com/inkVerb/icons/blob/master/lmms-solid.svg

**Comment by JesseSteele** [comment]
I originally reported the issue here, it was closed, but the problem persists.
https://github.com/erikdubois/Surfn/issues/4#issuecomment-261722038

Love you, though. It's a good mix up, and useful with all the consolidating going on. :-)

**Comment by erikdubois** [comment]
ok done
