### ISSUE TITLE
Skypeforlinux icon

### ISSUE THREAD

**Issue by ffoxin** [erikdubois/Surfn#11]
Hi,
The Skypeforlinux is already updated from alpha version to the beta one.
However, icon for it is still with alpha sign.
![image](https://cloud.githubusercontent.com/assets/1023876/26356190/e92870b8-3fd3-11e7-9795-ec3db6c6329a.png)
Thanks.

**Comment by erikdubois** [comment]
ok thanks

**Comment by erikdubois** [comment]
no more alpha and beta just one icon skypeforlinux
