### ISSUE TITLE
Resize home icons

### ISSUE THREAD

**Issue by chuutatsu** [erikdubois/Surfn#12]
I just used Surfn icons from AUR and I found this:
![wrong](https://cloud.githubusercontent.com/assets/24815847/26752918/d77726e8-4884-11e7-8a1c-97043314f620.png)

Look closely. The home icons are too small, compared to the former Yltra-Flat's home icons.

![right](https://cloud.githubusercontent.com/assets/24815847/26752925/006582b6-4885-11e7-9ca8-6455a032a72f.png)

Resizing the home icons in Surfn would be nice. Thank you.

**Comment by erikdubois** [comment]
former was former
why
surfn icons are created to look good on many distro's - 62 to be exact
[Surfn icons have been tested on following distro's](http://erikdubois.be/sardi-visited/)
I will keep it in mind though - I am not saying no.

**Comment by chuutatsu** [comment]
I used Yltra before, and now I used Surfn as soon as I found out about it. 
To me right now, Surfn's icons are indeed more complete than its predecessor. And it was only that very small home icon that bothered me.

Well, I'd rather wait for further updates of Surfn if I can't find a way of fixing it myself.

PS. Keep up the good work.

**Comment by erikdubois** [comment]
sure you can fix it
these are svg files - i could give you png and you are scre..ed
Sardi and Surfn are meant to be edited by the users.
open in inkscape and save with bigger height and width
I am sure you find something on my youtube channel or others

**Comment by chuutatsu** [comment]
For a quick test I replaced the every files of _go-home_ and _go-home-symbolic_ inside Surfn with the ones from the old Yltra.

![right](https://cloud.githubusercontent.com/assets/24815847/26753455/fa5d48e8-4890-11e7-80f6-93b4d4f4b922.png)

Now the home icons appears bigger as the previous/back icons.

**Comment by erikdubois** [comment]
if you want to learn how to mix and use icons I can only suggest all these tutorials
i explain A LOT here
[http://erikdubois.be/personalize-sardi-icon-theme-overview/](http://erikdubois.be/personalize-sardi-icon-theme-overview/)

**Comment by chuutatsu** [comment]
Alright, thanks for the link. Bookmarking and reading it now.
