### ISSUE TITLE
Some icons are not shown correctly (too big or incomplete)

### ISSUE THREAD

**Issue by slaecker** [erikdubois/Surfn#13]
Some icons are too big in several applications, others are shown incomplete. In the example below the screenshot icon in remmina is shown too large compared to the others, the down arrow is shown incomplete. I've seen such things in several applications where other icon themes don't show such a behavior so I don't think the issue lies inside the applications.

![surfn-arc_remmina](https://user-images.githubusercontent.com/8582375/27102740-a4e99cce-5086-11e7-8f5b-98c016080568.png)

**Comment by erikdubois** [comment]
will investigate
thanks for reporting

**Comment by erikdubois** [comment]
can you check where this icon is coming from - the camera
I do not find it in surfn?

**Comment by slaecker** [comment]
On my system (Arch Linux), installed via [AUR](https://aur.archlinux.org/packages/surfn-icons-git/) using the Surfn-Arc variant I have the camera icons in the following directories:

```
> tree -P 'camera*' /usr/share/icons/Surfn/
/usr/share/icons/Surfn/
├── 128
├── 16
│   ├── actions
│   ├── animations
│   ├── apps
│   ├── devices
│   ├── mimetypes
│   └── status
├── 22
│   ├── actions
│   ├── animations
│   ├── apps
│   ├── devices
│   ├── mimetypes
│   └── status
├── 24
│   ├── actions
│   ├── animations
│   ├── devices
│   ├── mimetypes
│   └── status
├── 32
│   ├── actions
│   ├── animations
│   ├── devices
│   └── status
├── 48
│   ├── categories
│   └── devices
├── 64
├── 96
└── scalable
    ├── actions
    │   ├── scalable
    │   └── symbolic
    ├── animations
    ├── apps
    │   ├── scalable
    │   └── symbolic
    ├── categories
    │   ├── scalable
    │   └── symbolic
    │       ├── camera-photo-symbolic.svg
    │       ├── camera-video-symbolic.svg
    │       └── camera-web-symbolic.svg
    ├── devices
    │   ├── scalable
    │   │   └── camera-photo.svg
    │   └── symbolic
    │       ├── camera-photo-symbolic.svg
    │       ├── camera-video-symbolic.svg
    │       └── camera-web-symbolic.svg
    ├── emblems
    │   ├── scalable
    │   └── symbolic
    ├── emotes
    │   └── symbolic
    ├── mimetypes
    │   ├── scalable
    │   └── symbolic
    ├── notifications
    │   └── scalable
    ├── panel
    │   ├── scalable
    │   └── symbolic
    ├── places
    │   ├── scalable
    │   └── symbolic
    │       ├── camera-photo-symbolic.svg
    │       ├── camera-video-symbolic.svg
    │       └── camera-web-symbolic.svg
    └── status
        ├── scalable
        └── symbolic

64 directories, 10 files
```
Keep up the good work, I love this icon pack!

**Comment by erikdubois** [comment]
will try
thanks for the help

**Comment by erikdubois** [comment]
it is this one
Surfn/scalable/devices/scalable/camera-photo.svg

**Comment by erikdubois** [comment]
done closing let me know if all is well

**Comment by erikdubois** [comment]
uninstall and reinstall surfn

**Comment by slaecker** [comment]
Solved, many thanks.

BTW, the down arrow problem was a misunderstanding. Checking the icons folder the icon used here is the "bottom" icon, not the "down" icon ;)
