### ISSUE TITLE
WPS office icons in Xfce menu too big

### ISSUE THREAD

**Issue by spsf64** [erikdubois/Surfn#15]
It works fine in whisker menu though, check attached images
Thanks for this beautiful icon theme!

![xfce](https://user-images.githubusercontent.com/1877391/27381127-f7e4be1e-5657-11e7-8392-a092362504e7.png)

![whisker](https://user-images.githubusercontent.com/1877391/27381137-fd5e7902-5657-11e7-8578-7944dc879625.png)

**Comment by erikdubois** [comment]
my guess is they do not exist
and come from somewhere else
check by deleting from index.theme
https://github.com/erikdubois/Surfn/blob/master/Surfn/index.theme
Inherits=Surfn,gnome,hicolor

delete gnome,hicolor

then delete cache file

then reselect
my guess is you do not have icons then

**Comment by erikdubois** [comment]
will need the icon names of the .desktop files of wps

**Comment by spsf64** [comment]
Thanks for replying Erik, but I am away from home and will be able to check only next week.
Hope someone else can check and report back.
Regards
edit: this is archlinux with xfce desktop

**Comment by erikdubois** [comment]
will fix it
download later today
no need for your input
know what to do

**Comment by spsf64** [comment]
@erikdubois just checked ver 9.2-7 and the wps icons are ok now!
Thanks
