### ISSUE TITLE
Surfn Arch Blue bug

### ISSUE THREAD

**Issue by LMint** [erikdubois/Surfn#18]
I really love this icon set, but there is a little problem with Surfn Arch Blue, the icon for the music folder doesn't scale properly and only stays at one size.

**Comment by erikdubois** [comment]
Can you tell me the operating system - resolution (4k) - what application -  a picture

**Comment by LMint** [comment]
I'm using Linux Mint 18 with a 1366x768 resolution and this happens with any file manager application. Here's a screenshot of my home folder.

![captura de pantalla de 2017-07-12 21-08-25](https://user-images.githubusercontent.com/30103020/28102715-10f97d0c-669f-11e7-9885-b92cd73870f8.png)

**Comment by erikdubois** [comment]
thanks

**Comment by erikdubois** [comment]
which linux mint is this
cinnamon...xfce...mate

**Comment by erikdubois** [comment]
test this for me
go to surfn arch blue
delete all folders but the scalable
delete icon-theme.cache
select other icon theme and select again surfn arch blue
i think this will fix it

**Comment by erikdubois** [comment]
all seems fine in linux mint 18.2 cinnamon

**Comment by LMint** [comment]
Hi, I tried deleting the folders you said and icon-theme.cache and it scales now but it shows a generic folder icon instead of the music folder one. And yes, my system is Linux Mint 18.2 Cinnamon.

**Comment by erikdubois** [comment]
picture please
as here all works

**Comment by LMint** [comment]
Here it is.
![captura de pantalla de 2017-07-13 20-04-17](https://user-images.githubusercontent.com/30103020/28127433-89f1fdd2-66fa-11e7-83c6-e393fc296993.png)

**Comment by erikdubois** [comment]
Is it possible you have deleted that folder
then created a folder of your own and named it

**Comment by erikdubois** [comment]
try xdg-user-dirs-update if you have it
delete the music folder first

**Comment by LMint** [comment]
Alright, deleted music folder, tried xdg-user-dirs-update and rebooted, it didn't work.
![captura de pantalla de 2017-07-13 20-20-50](https://user-images.githubusercontent.com/30103020/28128310-500a6a8e-66fd-11e7-9002-68cefb60052b.png)

**Comment by erikdubois** [comment]
I think the answer is in there
Google how to get the original folders back
Check/change to other icon themes
I bet they have the same problem
Op wo 12 jul. 2017 om 18:26 schreef LMint <notifications@github.com>

**Comment by LMint** [comment]
I managed to restore the original music folder back. Here I am using the default Surfn icons and as you can see this is only a problem of Surfn Arch Blue.

![captura de pantalla de 2017-07-13 20-50-05](https://user-images.githubusercontent.com/30103020/28129412-392a203a-6701-11e7-9886-d57e4802c729.png)

**Comment by erikdubois** [comment]
This looks normal

Sent from my ipad. Embrace my typo's and short answers.

**Comment by LMint** [comment]
So there's no way to fix it? maybe messing with the files inside...

**Comment by erikdubois** [comment]
I can not recreate your problem

Sent from my ipad. Embrace my typo's and short answers.

**Comment by LMint** [comment]
Maybe its just a problem with Debian-based distros, I'll try to see what I can do.

**Comment by LMint** [comment]
I fixed it, it seems that Surfn Arch Blue was missing the folder-music.svg file in scalable/places, so I downloaded Yltra Flat Arch Blue (which doesn't have this problem) and copied the folder-music.svg file found in places/scalable and pasted it in surfn arch blue/scalable/places.

**Comment by erikdubois** [comment]
We should have checked that first - shouldn't we 
I have added this icon to surfn arch blue now

**Comment by LMint** [comment]
Just one more thing, I had to delete icon-theme.cache in order to make it work.

**Comment by erikdubois** [comment]
that is normal
