### ISSUE TITLE
Problem with icon being displayed as a too big "X"

### ISSUE THREAD

**Issue by spsf64** [erikdubois/Surfn#19]
I don't know what icon is that, but you can check in the screenshots, the programs are:
PulseEffects and Curlew.
The first pic is using Papirus-Dark and the second with Surfn-Papirus
The problem occurs with all surfn variations...
TIA

![papirus-original](https://user-images.githubusercontent.com/1877391/28383618-20e182ba-6c98-11e7-868c-d8feadbaa35a.png)

![papirussurfn](https://user-images.githubusercontent.com/1877391/28383622-29aed5e6-6c98-11e7-8e80-51b1d7e78b89.png)

![papirussurfnmarked](https://user-images.githubusercontent.com/1877391/28383788-c0c4be8c-6c98-11e7-9ffe-fbb1d9808a0f.png)

**Comment by erikdubois** [comment]
issue solved

**Comment by spsf64** [comment]
Just updated the pack from AUR, working 100%.
As always, these icons are GREAT!
Thank you!
