### ISSUE TITLE
Folder scaling issue

### ISSUE THREAD

**Issue by gotolindak73** [erikdubois/Surfn#2]
I'm a fan of the Super-Ultra-Flat-Numix-Remix iconsets. I use a 4K monitor on which I need to use zoomed folders. If I go above 100% say 150% or 200% the folders on some of the sets do not scale up properly. What happens i that the folder size stays the same and the spacing between folders increase. The Super-Ultra-Flat-Numix-Remix works and the arc version but not the orange or majestic for example. The new Papirus set has the same issues. 
Attaching two Nemo screenshots so you can se what I mean. 
![skarmbild fran 2016-08-23 22-40-14](https://cloud.githubusercontent.com/assets/20610372/17908955/c2a5915a-6982-11e6-8a83-37d4e16668aa.png)
![skarmbild fran 2016-08-23 22-40-36](https://cloud.githubusercontent.com/assets/20610372/17908956/c2a9c3c4-6982-11e6-82a6-ad8d843e2f8a.png)

**Comment by erikdubois** [comment]
I will look into it

Sent from my iphone. Embrace the typos and the short answers.

**Comment by erikdubois** [comment]
I added scalable folders for places and actions to all of the icon sets.
This issue should be fixed now and for all the icon sets.
Can you report back if it is so I can close this issue.
Thanks for reporting so I can make this icon theme even better.
