### ISSUE TITLE
Suggestion: change some icons displayed in xfce whisker menu

### ISSUE THREAD

**Issue by spsf64** [erikdubois/Surfn#22]
Comparing Surfn-Papirus-Blue with Papirus-Dark (from AUR) I think standard Papirus have a better looking for some categories.
Please check the icons of: All, Accessories, Other and System
I think "System" is better represented with the "gear" icon, while the other 3 could be a bit different just to be more visual appealing.
TIA
See attached images...

Surfn Papirus Blue:
![surfn-papirus-blue](https://user-images.githubusercontent.com/1877391/30712606-f4d39960-9ee2-11e7-8719-3d3bec618994.png)

Papirus Dark:
![papirus-dark](https://user-images.githubusercontent.com/1877391/30712612-fc8dabb4-9ee2-11e7-9935-86e3153073f3.png)

**Comment by erikdubois** [comment]
You can change your Surfn theme anyway you see fit. All tutorials are on
htts://erikdubois.be
It is quite easy to change these icons and make 'a mix' of different themes
Enjoy

Op do 21 sep. 2017 om 20:39 schreef Sergio Schneider <
notifications@github.com>:

**Comment by spsf64** [comment]
Thanks, I will check later!
