### ISSUE TITLE
Suggestion: green Surfn Luv

### ISSUE THREAD

**Issue by karl69942** [erikdubois/Surfn#23]
I made one of these "issue" things but it disappeared already :S sorry if you already took it down, I don't know what happened to it. It would be super cool to have a Surfn Luv Green, I really like your Surfn Luv & Surfn Luv Red icons!! They're beautiful!

**Comment by erikdubois** [comment]
You can make those yourself with scripts. They are included in the Sardi icons at sourceforge.
There are 16 million colours. Your green is just one of them. Follow tutorials on https://erikdubois.be to know how.
