### ISSUE TITLE
App icon for Tilix (renamed Terminix)

### ISSUE THREAD

**Issue by RohanVilloth** [erikdubois/Surfn#24]
Terminix recently renamed itself to Tilix. Surfn already has a Terminix icon at [/scalable/apps/scalable/terminix.svg](https://github.com/erikdubois/Surfn/blob/9.2.8/Surfn/scalable/apps/scalable/terminix.svg) and a symlink at [/scalable/apps/scalable/com.gexperts.Terminix.svg](https://github.com/erikdubois/Surfn/blob/9.2.8/Surfn/scalable/apps/scalable/com.gexperts.Terminix.svg). It needs another symlink for:

    Icon=com.gexperts.Tilix

**Comment by erikdubois** [comment]
ok thanks

**Comment by erikdubois** [comment]
done

**Comment by RohanVilloth** [comment]
Thanx @erikdubois ! :relaxed:
