### ISSUE TITLE
Ubuntu Budgie distributor logo

### ISSUE THREAD

**Issue by RohanVilloth** [erikdubois/Surfn#25]
Most distros provide a distributor logo, usually named `distributor-logo-<distro-name>`. Surfn has provided [distributor-logo.svg](https://github.com/erikdubois/Surfn/blob/9.2.8/Surfn/scalable/apps/scalable/distributor-logo.svg). Ubuntu Budgie has `distributor-logo-ubuntu-budgie`.

**Budgie Welcome** uses it as the app icon. So, for providing icon for Budgie Welcome, the distributor logo's needed. For eg, Moka provides [distributor-logo-ubuntu-budgie.svg](https://github.com/snwh/moka-icon-theme/blob/v5.3.6/Moka/48x48/places/distributor-logo-ubuntu-budgie.png).

Icon themes usually provide an icon derived from the specific distro's logo. Here's Ubuntu Budgie's logo: [Link](https://github.com/UbuntuBudgie/assets/blob/master/Logos/budgie-remix-logo-large-inverted.svg)

**Comment by erikdubois** [comment]
ok that is on the to do list
thank you for getting back to me
sardi will probably be the same issue
will check it

2017-09-28 21:43 GMT+02:00 HEXcube <notifications@github.com>:

**Comment by erikdubois** [comment]
done
