### ISSUE TITLE
[xfce4]Batterie and Bluetooth status icons not changing. 

### ISSUE THREAD

**Issue by volklord** [erikdubois/Surfn#3]
The Batterie status icon shows a full charged Batterie icon, even if it's absent (removed). The Bluetooth icon also doesn't change when connected/disconnected.

One more thing, is it possible to use this icon theme with KDE/Plasma5?

Thanks
![screenshot_2016-10-10_04-49-06](https://cloud.githubusercontent.com/assets/20864876/19226134/557e9f8c-8ea7-11e6-87a8-b71afe5cdbe3.png)

**Comment by erikdubois** [comment]
KDE/Plasma 5 has been tested.
Just all the games have not been sardinized
can you give me a screenfetch info - distro... so I can reproduce the issue

**Comment by volklord** [comment]
- So I just tested it again and the missing Batterie icon is shown, seems to be a 'false-positive', sorry for that. Nevertheless I have a suggestion, I think it would be better to use the Batterie icons (1st) instead of generic icons (2nd)....
  ![screenshot_2016-10-10_20-55-12](https://cloud.githubusercontent.com/assets/20864876/19248009/e019db26-8f2d-11e6-8a98-5c388e96ca4b.png)
  ![screenshot_2016-10-10_20-56-33](https://cloud.githubusercontent.com/assets/20864876/19248016/ea47b2e4-8f2d-11e6-90c3-1fb91f715d57.png)
- The Bluetooth icon doesn't change, so one can't tell if a mouse/headphone is connected/disconnected, but actually the icons are included in the theme...
  ![screenshot_2016-10-10_21-14-04](https://cloud.githubusercontent.com/assets/20864876/19248170/c2c02ac0-8f2e-11e6-8216-254ac241a76b.png)
  - Distro Infos
    ![screenshot_2016-10-10_19-55-49](https://cloud.githubusercontent.com/assets/20864876/19248516/cf6fd4c6-8f30-11e6-9670-73d8efb2d5ee.png)
    ## By the way, thanks for the nice theme and for your time you invest.

**Comment by erikdubois** [comment]
thanks for the appreciation for the work and the time invested in this project
