### ISSUE TITLE
xfce4 reboot icon problematic

### ISSUE THREAD

**Issue by tulliana** [erikdubois/Surfn#32]
xfce4 reboot icon (reboot and system-reboot icons) problematic. I guess it needs to be a more prominent icon. Must be corrected at the first opportunity. 

Best regards..
![Ekran görüntüsü_2019-09-03_18-23-16](https://user-images.githubusercontent.com/2324162/64186856-3a3d3d00-ce78-11e9-90f4-da012d1153ae.png)

**Comment by erikdubois** [comment]
solved - grey background now
