### ISSUE TITLE
Icon request: Discord

### ISSUE THREAD

**Issue by Maik93** [erikdubois/Surfn#35]
Hi, great icon pack!
One icon is missing: Discord! Can you add it?
The original one (in svg) can be found here: https://discordapp.com/branding
I've installed it through snap, so the .desktop path is this:
```
Icon=/snap/discord/93/usr/share/discord/discord.png
```
I don't know how to do this on my own, if you guide me in this I can help you in the future ;)

**Comment by erikdubois** [comment]
we have discord
can you check again

Op vr 25 okt. 2019 om 18:38 schreef Maik93 <notifications@github.com>:

**Comment by Maik93** [comment]
mmm maybe it is not recognised because it is installed through snap (from Ubuntu software center)... This problem can be easily fixed (not by reinstalling it though apt)?
