### ISSUE TITLE
Icon not displayed for Onlyoffice (archlinux)

### ISSUE THREAD

**Issue by spsf64** [erikdubois/Surfn#36]
Not sure if the problem is related to the AUR package or the icon is missing from Surfn?
The aur package is located at: https://aur.archlinux.org/packages/onlyoffice-bin

**Comment by erikdubois** [comment]
They have changed the name
Icon=onlyoffice-desktopeditors

**Comment by spsf64** [comment]
So, is there any solution?

**Comment by erikdubois** [comment]
sure

Op do 28 mei 2020 om 00:20 schreef Sergio Schneider <
notifications@github.com>:

**Comment by erikdubois** [comment]
Fixed 20.5.2 version

**Comment by spsf64** [comment]
Thanks, working perfectly!
