### ISSUE TITLE
keepass*.svg do not work properly

### ISSUE THREAD

**Issue by krem** [erikdubois/Surfn#39]
Hello, keepass*.svg fail to be rendered properly for me - just green or blue background. 
Tested files in Chromium, other recent image viewers - all failed, though for some reason XnViewMP renders them fine.

OS: Arch Linux 
Kernel: x86_64 Linux 5.14.5-arch1-1
Resolution: 1920x1080
DE: Xfce4
WM: Xfwm4
WM Theme: Default
GTK Theme: Adwaita-dark [GTK2]
Icon Theme: Surfn

**Comment by erikdubois** [comment]
next release
