### ISSUE TITLE
LMMS is using the Ardour icon

### ISSUE THREAD

**Issue by JesseSteele** [erikdubois/Surfn#4]
I based this on your folder svg. I have one made of all triangles, this is simple-flat.
Merge this:
https://github.com/inkVerb/icons/blob/master/lmms-solid.svg

I'm sending the same thing to yltra-flat-icon-theme.
Love.

**Comment by erikdubois** [comment]
There is already an icon for lmss.

**Comment by JesselSteele** [comment]
Why does the Ardour icon show in its place?

**Comment by JesseSteele** [comment]
In GNOME, LMMS displays the flat Ardour icon.
In Unity, LMMS displays the original icon, not any special "flat" icon.

**Comment by erikdubois** [comment]
I ll check it
Op do 17 nov. 2016 om 20:01 schreef Jesse Steele notifications@github.com

**Comment by JesseSteele** [comment]
You may use, modify, adopt, copy my icon here. I made it for you and the crew.
https://github.com/inkVerb/icons/blob/master/lmms-solid.svg

**Comment by erikdubois** [comment]
thanks

**Comment by erikdubois** [comment]
I am looking into the matter.
I have installed ardour and Lmms
both have all the icons they need in all core sardi icon sets.
But the problem is not on linux mint
You talk of Unity. On which version and distro of Ubuntu is this occurring?

2016-11-19 16:33 GMT+01:00 Jesse Steele notifications@github.com:

**Comment by JesseSteele** [comment]
This photo is from Ubuntu 16.10 GNOME, Surfn-Breeze-Dark
My Instagram shot:
https://www.instagram.com/p/BT_U8IhhM1O

Use either one:
https://github.com/inkVerb/icons/blob/master/lmms-layers.svg
https://github.com/inkVerb/icons/blob/master/lmms-solid.svg
