### ISSUE TITLE
Surfn Majestic stock folder problem

### ISSUE THREAD

**Issue by tulliana** [erikdubois/Surfn#40]
On (Archman Linux= Arch based) Xfce-Thunar the user directory still appears blue when I select the Surfn Majestic icons. It should appear as the Surfn Majestic folder icon.

Can we also include the Archman Linux launch icon in the Surfn Icon pack. I added it as an svg file below

Best regards
On behalf of the Archman Linux team, project manager @tulliana

![archman-surfn-icons](https://user-images.githubusercontent.com/2324162/167187632-86f2823b-a4ac-4b75-8821-2c7c7acaaa34.png)

**Comment by tulliana** [comment]
Archman Start Logo: https://gitlab.com/Archman-OS/archman-start/-/blob/main/archman-logo.svg

**Comment by erikdubois** [comment]
logo is in

I need what that blue thing is...

**Comment by erikdubois** [comment]
i have got an idea
the icon we see is coming from ARC
so check surfn-arc - places folder
one of those links/icons is what is displayed
so we are missing one icon or link

**Comment by erikdubois** [comment]
Did you figure it out?
I am now developing the icons
I have no issue on xfce4 on ArcoLinux
![normal](https://user-images.githubusercontent.com/10594806/194507287-b338794b-6a98-46f6-9626-413a5c549950.png)

**Comment by tulliana** [comment]
![archman-xfce-surfn-icons](https://user-images.githubusercontent.com/2324162/211639012-4fa7746c-da7d-4ed1-b781-c1ad8143e6a6.png)
Looks great. Sorry I'm late for feedback. Thanks.
