### ISSUE TITLE
Firewalld app icon missing on Xfce

### ISSUE THREAD

**Issue by tulliana** [erikdubois/Surfn#41]
The icon of the **Firewalld** application is not visible on Archman Xfce. The screenshot is below.
![firewalld missing icon](https://user-images.githubusercontent.com/2324162/216969314-14893894-1478-4db6-a283-f09ed3ab783a.png)

Best regards..

**Comment by erikdubois** [comment]
done

**Comment by tulliana** [comment]
Thanks. Which commit should I look at?

**Comment by erikdubois** [comment]
one of the last ones
