### ISSUE TITLE
Dark mode missing icons in kate text editor

### ISSUE THREAD

**Issue by marcomalix** [erikdubois/Surfn#43]
Hello Erik, 
I am using Surfn-Numixs icons in Debian 12 with Plasma as DE (screenfetch below), a little issue with the text editor kate where some icons are not suitable for dark mode as shown in the pic below 

![image](https://github.com/erikdubois/Surfn/assets/88252252/9942d72b-6095-4fa5-b8b5-c9f670848eeb)

![image](https://github.com/erikdubois/Surfn/assets/88252252/701248bd-127c-42c7-b838-78d5e814c7f7)

Thank you for your great work.

**Comment by erikdubois** [comment]
I have made you a video on Debian 12 Plasma to show you that you need different icons when on Plasma.

Use the icons created for Plasma
https://www.erikdubois.be/sardi-surfn-visited
https://github.com/erikdubois/Surfn-Plasma-Dark
https://github.com/erikdubois/Surfn-Plasma-light
https://github.com/erikdubois/Surfn-Plasma-Dark-Tela
https://github.com/erikdubois/Surfn-Plasma-Flow

https://youtu.be/h_V7wONJNT8

![image](https://github.com/erikdubois/Surfn/assets/10594806/48cff776-6c7a-4797-bfc3-02f22ffe362d)

Closing this for now. 
You can re-open when needed.
