### ISSUE TITLE
A Handful of Missing Icons

### ISSUE THREAD

**Issue by MggMuggins** [erikdubois/Surfn#7]
I really love your Ultra Flat theme, but I use a lot of apps that aren't included. I'm assuming the missing cursors section describes the steps for suggesting new icons, as well as letting you know about fixing broken ones. Anyway, here are some icons that aren't a part of your iconset (so of course they don't appear anywhere) that would be cool to have:
### Pithos
```Icon=pithos```
This is a lightweight client music player for the internet streaming service Pandora. The default Icon is a Pithos (Greek Pot) with a music note.
### JD-GUI
```Icon=jd-gui```
Nice Java Decompiler. Steaming Coffee Mug is the original icon.
### Sli3er
```Icon=slic3r```
A program to generate G-Code for 3D Printers. Pretty fast a lightweight. Original Icon is a circle that has been bisected diagonally and then slid along the cut.
### OpenSCAD
```Icon=openscad```
A 3D CAD software that uses code instead of a gui to create shapes. Original icon is a sphere that has had a cylinder subtracted from it along all three axis.
### MuseScore
```Icon=mscore```
Music Composition program, completely open-source and free alternative to Finale Notepad. Original Icon is a circle with "mu" and a fermata over the u.

I'll add the original icons for all of these later. Need to switch desktop environments right now...

**Comment by erikdubois** [comment]
thanks for reporting
going on the to do list

**Comment by MggMuggins** [comment]
When you do get this stuff done, how do I update? I've already forgotten how I installed it....

**Comment by MggMuggins** [comment]
Also the Ubuntu Software center does not appear to have an icon.

**Comment by erikdubois** [comment]
For the ubuntu software center
you need to supply the contents of the ubuntu software center .desktop file
in /usr/share/applications
so I can check

**Comment by MggMuggins** [comment]
```
[Desktop Entry]
Name=Software
Comment=Add, remove or update software on this computer
Icon=org.gnome.Software
Exec=gnome-software %U
Terminal=false
Type=Application
Categories=GNOME;GTK;System;PackageManager;
Keywords=Updates;Upgrade;Sources;Repositories;Preferences;Install;Uninstall;Program;Software;App;Store;
StartupNotify=true
MimeType=x-scheme-handler/appstream;
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=gnome-software
X-GNOME-Bugzilla-Component=gnome-software
X-GNOME-UsesNotifications=true
DBusActivatable=true
X-Ubuntu-Gettext-Domain=gnome-software
```

**Comment by erikdubois** [comment]
The icon org.gnome.Software.svg exists in apps/scalable.
It might be that it does not look ok in /usr/share/applications
it must be ok in the rest of the system.
![surfn](https://user-images.githubusercontent.com/10594806/27511160-c01add50-591e-11e7-9d39-21e37b512f5c.jpg)

**Comment by erikdubois** [comment]
pithos has been added

**Comment by erikdubois** [comment]
jd-gui done

**Comment by erikdubois** [comment]
openscad done

**Comment by erikdubois** [comment]
musescore done

**Comment by erikdubois** [comment]
If there are more to create...
one issue per icon
read the guidelines 
slic3r unknown

**Comment by MggMuggins** [comment]
Alright, thank you very much! Now I get to figure out how to install this thing again...
