### ISSUE TITLE
xed editor and toolbar icons issue

### ISSUE THREAD

**Issue by ghost** [erikdubois/Surfn#8]
Hi Erik, I really love your Surfn icon theme, but I'm having a problem with xed editor toolbar (my linux distro is Linux Mint 18.1 and xed version is 1.2.2). The past icon is very ugly (bigger than others) and I think that xed isn't using symbolic icons from your icon theme. What's wrong? Attacched you can find a screenshot showing the issue.

![screenshot_2017-04-24_06-20-30](https://cloud.githubusercontent.com/assets/27941267/25322636/f6e85268-28b8-11e7-81d7-3fe6ed5b2daa.png)

Thanks a lot for your works, waiting for a reply.

**Comment by erikdubois** [comment]
yes that is strange
i will look into it
i will need linux mint 18.1 CINNAMON ? with xed 1.2.2 right?
did you try putting this icon in one of the folders marked 16/actions or 22/actions and make it a bit smaller (if needed)that might do the trick) - they are svg... so you can change them

**Comment by ghost** [comment]
Sorry, I haven't specified desktop type, I use Linux Mint version 18.1 with Xfce4...
So, I'll try to copy the specified icon in 16/actions or 22/actions..

**Comment by ghost** [comment]
Great! Copying scalable/actions/scalable/edit-paste-symbolic.svg in 22/actions/ works great!

![screenshot_2017-04-24_08-34-33](https://cloud.githubusercontent.com/assets/27941267/25324936/e65b57b4-28c8-11e7-965e-bad97a79fc0f.png)

Thanks a lot :-)

**Comment by erikdubois** [comment]
thought so

**Comment by erikdubois** [comment]
i have updated github accordingly
thanks for helping
