### ISSUE TITLE
Some icon issues

### ISSUE THREAD

**Issue by ghost** [erikdubois/Surfn#9]
Hi Erik, I would like to point out two little problems I've found using your icon theme...

Always referring to Linux Mint 18.1 with Xfce4, in "File Operation progress" window is used hicolor theme icon (hicolor/16x16/stock/navigation/stock_folder-copy.png, hicolor/24x24/stock/navigation/stock_folder-copy.png, hicolor/16x16/stock/navigation/stock_folder-move.png and hicolor/24x24/stock/navigation/stock_folder-move.png):

![screenshot_2017-04-25_15-46-40](https://cloud.githubusercontent.com/assets/27941267/25389635/75928386-29d1-11e7-9989-00f971680108.png)

I fixed it copying two icons, folder-copy.svg and folder-move.svg in Surfn/scalable/actions/scalable/ and creating two symlinks, stock_folder-copy.svg and stock_folder-move.svg:

![screenshot_2017-04-25_14-55-15](https://cloud.githubusercontent.com/assets/27941267/25389664/8646f31a-29d1-11e7-8d7a-3ca65519f6aa.png)

Furthermore, for xfce4-hotcorner-plugin (your display icon results too big, especially in panel bar) I've created an icon called xfce4-display.svg smaller than yours display.svg, monitor.svg and video-display.svg located in Surfn/scalable/devices/scalable/:

![hotcorner-1](https://cloud.githubusercontent.com/assets/27941267/25390171/091cd290-29d3-11e7-84d3-9f6242d7ce4d.png)

![hotcorner-2](https://cloud.githubusercontent.com/assets/27941267/25390172/091e9fc6-29d3-11e7-9ad7-2f59cb42e1e7.png)

this is my new icon:
[xfce4-display.svg.zip](https://github.com/erikdubois/Surfn/files/955316/xfce4-display.svg.zip)

which looks as follows:

![hotcorner-3](https://cloud.githubusercontent.com/assets/27941267/25390250/40d29f30-29d3-11e7-89f8-8add762d22ff.png)

![hotcorner-4](https://cloud.githubusercontent.com/assets/27941267/25390253/416cdbc2-29d3-11e7-8313-5e03b8d4e813.png)

Please, if my suggestions are incorrect, feel free to correct me.
I hope to do a good thing with these two suggestions.
Greetings.

**Comment by erikdubois** [comment]
looks good 
will take a look and incorporate

**Comment by erikdubois** [comment]
done
